cmarket/Controllers/BackendController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cmarket.Models;
using MySql.Data.MySqlClient;
using System.Text;
using System.Text.RegularExpressions;
using System.Security.Cryptography;
using PagedList;



namespace cmarket.Controllers
{
    public class BackendController : Controller
    {
        // GET: Backend
        string constr = ConfigurationManager.ConnectionStrings["connectmysql"].ConnectionString;
        public ActionResult Index()
        {
            //ViewData["data"] = "pindex";
            //TempData["data"]
            TempData["data"] = "pindex";
            return View("index");
        }

        // GET: Backend/Details/5
        public ActionResult owner_land(int type_status_regis)
        {
            //ViewBag.Message = "owner_land";
            TempData["data"] = "owner_land";
            TempData["keymenu"] = "owner_land";
            MySqlConnection connection = new MySqlConnection(constr);
            List<adminModel> owland = new List<adminModel>();
            connection.Open();

            MySqlCommand command = connection.CreateCommand();


            if (type_status_regis==1) { 
            command.CommandText = "select * from tb_regfarmer as ow " +
                 "left join province as p on(p.PROVINCE_ID=ow.PROVINCE_ID)" +
                 "left join amphur as a on(a.AMPHUR_ID=ow.AMPHUR_ID)" +
                 "left join district as d on(d.DISTRICT_ID=ow.DISTRICT_ID) where type_status_regis='1' order by ow.far_id asc";
            }

            if (type_status_regis == 2)
            {
                command.CommandText = "select * from tb_regfarmer as ow " +
                     "left join province as p on(p.PROVINCE_ID=ow.PROVINCE_ID)" +
                     "left join amphur as a on(a.AMPHUR_ID=ow.AMPHUR_ID)" +
                     "left join district as d on(d.DISTRICT_ID=ow.DISTRICT_ID) where type_status_regis='2' order by ow.far_id asc";
            }

            MySqlDataReader reader = command.ExecuteReader();



            while (reader.Read())
            {

                owland.Add(new adminModel
                {
                    far_id = Convert.ToInt32(reader["far_id"]),
                    far_name = reader["far_name"].ToString(),
                    far_surname = reader["far_surname"].ToString(),
                    id_card = reader["id_card"].ToString(),
                    far_tel = reader["far_tel"].ToString(),
                    PROVINCE_NAME = reader["PROVINCE_NAME"].ToString(),
                    AMPHUR_NAME = reader["AMPHUR_NAME"].ToString(),
                    DISTRICT_NAME = reader["DISTRICT_NAME"].ToString(),
                 
                    

                });
            }


            reader.Close();
            ViewBag.owland = owland;
            ViewData["type_status_regis"] = type_status_regis;
            return View("index");
        }



        public ActionResult owner_land_orga(int type_status_regis_og)
        {
            //ViewBag.Message = "owner_land";
            TempData["data"] = "owner_land_orga";
            TempData["keymenu"] = "owner_land_orga";
            MySqlConnection connection = new MySqlConnection(constr);
            List<adminModel> owland = new List<adminModel>();
            connection.Open();

            MySqlCommand command = connection.CreateCommand();


            if (type_status_regis_og == 1)
            {
                command.CommandText = "select * from regis_organi as ow " +
                 "left join province as p on(p.PROVINCE_ID=ow.PROVINCE_ID)" +
                 "left join amphur as a on(a.AMPHUR_ID=ow.AMPHUR_ID)" +
                 "left join district as d on(d.DISTRICT_ID=ow.DISTRICT_ID) where type_status_regis_og='1' order by ow.reg_organi_id asc";
            }

            if (type_status_regis_og == 2)
            {
                command.CommandText = "select * from regis_organi as ow " +
                 "left join province as p on(p.PROVINCE_ID=ow.PROVINCE_ID)" +
                 "left join amphur as a on(a.AMPHUR_ID=ow.AMPHUR_ID)" +
                 "left join district as d on(d.DISTRICT_ID=ow.DISTRICT_ID) where type_status_regis_og='2' order by ow.reg_organi_id asc";
            }
            MySqlDataReader reader = command.ExecuteReader();



            while (reader.Read())
            {

                owland.Add(new adminModel
                {
                    reg_organi_id = Convert.ToInt32(reader["reg_organi_id"]),
                    reg_name = reader["reg_name"].ToString(),
                    reg_regis_name = reader["reg_regis_name"].ToString(),
                    reg_regis_tel = reader["reg_regis_tel"].ToString(),
                    PROVINCE_NAME = reader["PROVINCE_NAME"].ToString(),
                    AMPHUR_NAME = reader["AMPHUR_NAME"].ToString(),
                    DISTRICT_NAME = reader["DISTRICT_NAME"].ToString(),
                    reg_status = reader["reg_status"].ToString(),



                });
            }


            reader.Close();
            ViewBag.owland = owland;
            ViewData["type_status_regis_og"] = type_status_regis_og;
            return View("index");
        }

        public ActionResult landOwner(int type_owner_land)
        {
            TempData["data"] = "landOwner";
            TempData["keymenu"] = "landOwner";
            TempData["type_owner_land"] = type_owner_land;
            MySqlConnection connection = new MySqlConnection(constr);
            List<adminModel> land = new List<adminModel>();
            connection.Open();

            MySqlCommand command = connection.CreateCommand();

            if (type_owner_land == 1) { 
                command.CommandText = "select " +
                "t.name_type,po.far_name,po.far_surname,ow.o_land_id,p.PROVINCE_NAME,a.AMPHUR_NAME,d.DISTRICT_NAME,ow.dsave,ow.m_rent,ow.place_land,ow.status_land,ow.land_rai,ow.land_nga,ow.land_va,ow.o_land_num from owner_land as ow " +
                "left join tb_regfarmer as po on(po.far_id=ow.id_owner)" +
                "left join province as p on(p.PROVINCE_ID=ow.PROVINCE_ID)" +
                "left join amphur as a on(a.AMPHUR_ID=ow.AMPHUR_ID)" +
                "left join district as d on(d.DISTRICT_ID=ow.DISTRICT_ID)" +
                "left join type_land as t on(t.type_land_id=ow.type_land_id)" +
                "where ow.type_owner_land='" + type_owner_land + "'" +

                "GROUP BY ow.o_land_id,p.PROVINCE_NAME,a.AMPHUR_NAME,d.DISTRICT_NAME,ow.dsave order by ow.o_land_id,po.far_id,ow.status_land asc";

                MySqlDataReader reader = command.ExecuteReader();


                while (reader.Read())
                {

                    land.Add(new adminModel
                    {
                        o_land_id = Convert.ToInt32(reader["o_land_id"]),
                        PROVINCE_NAME = reader["PROVINCE_NAME"].ToString(),
                        AMPHUR_NAME = reader["AMPHUR_NAME"].ToString(),
                        DISTRICT_NAME = reader["DISTRICT_NAME"].ToString(),
                        dsave = reader["dsave"].ToString(),

                        m_rent = reader["m_rent"].ToString(),
                        place_land = reader["place_land"].ToString(),
                        status_land = reader["status_land"].ToString(),
                        land_rai = reader["land_rai"].ToString(),
                        land_nga = reader["land_nga"].ToString(),
                        land_va = reader["land_va"].ToString(),
                        o_name = reader["far_name"].ToString(),
                        o_surname = reader["far_surname"].ToString(),
                        name_type = reader["name_type"].ToString(),
                        o_land_num = reader["o_land_num"].ToString(),


                    });
                }
                reader.Close();

            }

            if (type_owner_land == 2)
            {
                command.CommandText = "select * from owner_land as ow " +
                "left join regis_organi as po on(po.reg_organi_id=ow.id_owner)" +
                "left join province as p on(p.PROVINCE_ID=ow.PROVINCE_ID)" +
                "left join amphur as a on(a.AMPHUR_ID=ow.AMPHUR_ID)" +
                "left join district as d on(d.DISTRICT_ID=ow.DISTRICT_ID)" +
                "left join type_land as t on(t.type_land_id=ow.type_land_id)" +
                "where ow.type_owner_land='" + type_owner_land + "'" +

                "GROUP BY ow.o_land_id,p.PROVINCE_NAME,a.AMPHUR_NAME,d.DISTRICT_NAME,ow.dsave order by po.reg_organi_id,ow.status_land asc";

                MySqlDataReader reader = command.ExecuteReader();


                while (reader.Read())
                {

                    land.Add(new adminModel
                    {
                        o_land_id = Convert.ToInt32(reader["o_land_id"]),
                        PROVINCE_NAME = reader["PROVINCE_NAME"].ToString(),
                        AMPHUR_NAME = reader["AMPHUR_NAME"].ToString(),
                        DISTRICT_NAME = reader["DISTRICT_NAME"].ToString(),
                        dsave = reader["dsave"].ToString(),

                        m_rent = reader["m_rent"].ToString(),
                        place_land = reader["place_land"].ToString(),
                        status_land = reader["status_land"].ToString(),
                        land_rai = reader["land_rai"].ToString(),
                        land_nga = reader["land_nga"].ToString(),
                        land_va = reader["land_va"].ToString(),
                        o_name = reader["reg_name"].ToString(),
                        //o_surname = reader["o_surname"].ToString(),
                        name_type = reader["name_type"].ToString(),


                    });
                }
                reader.Close();

            }


            

            ViewBag.land = land;

cmarket/Views/Backend/focus_land.cshtml
@using cmarket.Models
@model IEnumerable<adminModel>
<div class="page-header"><h1>พื้นที่ จ.@ViewBag.PROVINCE_NAME อ.@ViewBag.AMPHUR_NAME ต.@ViewBag.DISTRICT_NAME</h1></div>
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">เพิ่ม Latitude Longitude</div>
        <div class="panel-body">

            <form class="form-inline" role="form" id="f02" name="f01" method="post" action="@Url.Action("updatelalo", "Backend")">

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">Latitude</div>
                        <input class="form-control" type="text" name="latitude" id="latitude" placeholder="Latitude" value="@ViewData["latitude_land"]">
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">Longitude</div>
                        <input class="form-control" type="text" id="longitude" name="longitude" placeholder="Longitude" value="@ViewData["longitude_land"]">
                    </div>
                </div>

                <button type="submit" class="btn btn-success">บันทึก</button>
                <input class="form-control" type="hidden" id="o_land_id" name="o_land_id" value="@ViewBag.o_land_id" placeholder="o_land_id">
                <input class="form-control" type="hidden" id="PROVINCE_NAME" name="PROVINCE_NAME" value="@ViewBag.PROVINCE_NAME" placeholder="PROVINCE_NAME">
                <input class="form-control" type="hidden" id="AMPHUR_NAME" name="AMPHUR_NAME" value="@ViewBag.AMPHUR_NAME" placeholder="AMPHUR_NAME">
                <input class="form-control" type="hidden" id="DISTRICT_NAME" name="DISTRICT_NAME" value="@ViewBag.DISTRICT_NAME" placeholder="DISTRICT_NAME">
                <input class="form-control" type="hidden" id="type_owner_land" name="type_owner_land" value="@ViewBag.type_owner_land" placeholder="type_owner_land">
            </form>


        </div>
    </div>
</div>

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">เพิ่ม polygon รูปแปลง</div>
        <div class="panel-body">

            <form class="form-inline" role="form" id="f02" name="f02" method="post" action="@Url.Action("updatepolygon", "Backend")">

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">ลำดับ</div>
                        <input class="form-control" type="text" id="seq_number" name="seq_number" placeholder="ลำดับ">
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">Latitude</div>
                        <input class="form-control" type="text" name="latitude" id="latitude" placeholder="Latitude">
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">Longitude</div>
                        <input class="form-control" type="text" id="longitude" name="longitude" placeholder="Longitude">
                    </div>
                </div>



                <button type="submit" class="btn btn-success">บันทึก</button>
                <input class="form-control" type="hidden" id="o_land_id" name="o_land_id" value="@ViewBag.o_land_id" placeholder="o_land_id">
                <input class="form-control" type="hidden" id="PROVINCE_NAME" name="PROVINCE_NAME" value="@ViewBag.PROVINCE_NAME" placeholder="PROVINCE_NAME">
                <input class="form-control" type="hidden" id="AMPHUR_NAME" name="AMPHUR_NAME" value="@ViewBag.AMPHUR_NAME" placeholder="AMPHUR_NAME">
                <input class="form-control" type="hidden" id="DISTRICT_NAME" name="DISTRICT_NAME" value="@ViewBag.DISTRICT_NAME" placeholder="DISTRICT_NAME">
                <input class="form-control" type="hidden" id="type_owner_land" name="type_owner_land" value="@ViewBag.type_owner_land" placeholder="type_owner_land">
            </form>


        </div>
    </div>
</div>


<table width="100%" border="1" style="background-color:white;">
    @{
        var ii = 1;
    }

    <tr>
        <th style="width:0.5%;" height="40">ลำดับ</th>
        <th>latitude</th>
        <th>longitude</th>
        <th></th>
    </tr>
    @foreach (adminModel owland in ViewBag.owland)
    {

        <tr>
            <th style="text-align:center;">@owland.seq_number</th>
            <th width="18%" scope="row" style="padding-left:10px; padding-top:10px; padding-bottom:10px;">
                @owland.polygon_lata
            </th>
            <th width="18%" scope="row" style="padding-left:10px; padding-top:10px; padding-bottom:10px;">
                @owland.polygon_ing
            </th>
             <th width="18%" scope="row" style="padding-left:10px; padding-top:10px; padding-bottom:10px;">
                 <a style="color:red;" onclick="return confirm('ต้องการลบใช่หรือไม่?')" href="@Url.Action("delete_polygon", "Backend",new { polygon_land_id = owland.polygon_land_id,o_land_id1=ViewBag.o_land_id,PROVINCE_NAME1=ViewBag.PROVINCE_NAME,AMPHUR_NAME1=ViewBag.AMPHUR_NAME,DISTRICT_NAME1=ViewBag.DISTRICT_NAME,type_owner_land1=ViewBag.type_owner_land})" class="ad-remove">
                            <i class="fa fa-trash"></i> ลบ
            </th>
        </tr>
        ii++;
    }


</table>

cmarket/Views/Backend/list_landowner.cshtml
@using cmarket.Models
@model IEnumerable<adminModel>
@{
    if (@Session["staff_id"] == null)
    {


        <script type='text/javascript'> window.location.href = '@Url.Action("ladmin", "Backend")';</script>
    }
}
<div class="page-header"><h3>แปลงเจ้าของที่ดิน</small></h3></div>
<div class="panel panel-default">
    <!--<div class="panel-heading">
        <a href="#" data-column="0" class="toggle-vis btn btn-default btn-sm">Name</a>
        <a href="#" data-column="1" class="toggle-vis btn btn-default btn-sm">Position</a>
        <a href="#" data-column="2" class="toggle-vis btn btn-default btn-sm">Office</a>
        <a href="#" data-column="3" class="toggle-vis btn btn-default btn-sm">Age</a>
        <a href="#" data-column="4" class="toggle-vis btn btn-default btn-sm">Start date</a>
        <a href="#" data-column="5" class="toggle-vis btn btn-default btn-sm">Salary</a>
    </div>-->
    <div class="panel-body">
        @if (Convert.ToInt32(ViewData["type_owner_land"]) == 1)
        {
            <a href="@Url.Action("landOwner", "Backend", new { type_owner_land = 1 })">
                <button type="button" class="btn btn-success">บุคคลทั่วไป</button>
            </a>
            <a href="@Url.Action("landOwner", "Backend", new { type_owner_land = 2 })">
                <button type="button" class="btn btn-default">องค์กร กลุ่ม</button>
            </a>
        }

        @if (Convert.ToInt32(ViewData["type_owner_land"]) == 2)
        {
            <a href="@Url.Action("landOwner", "Backend", new { type_owner_land = 1 })">
                <button type="button" class="btn btn-default">บุคคลทั่วไป</button>
            </a>
            <a href="@Url.Action("landOwner", "Backend", new { type_owner_land = 2 })">
                <button type="button" class="btn btn-success">องค์กร กลุ่ม</button>
            </a>
        }
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="basic-datatable2">
            <thead>
                <tr>
                    <th>ลำดับ</th>
                    <th>ชื่อ-นามสกุล</th>
                    <th>เอกสารสิทธิ</th>
                    <th>เลขที่เอกสารสิทธิ</th>
                    <th>ไร่</th>
                    <th>งาน</th>
                    <th>ตารางวา</th>
                    <th>พื้นที่</th>

                    <th>สถานะ</th>
                    <th></th>
                </tr>
            </thead>

            <tfoot>
                <tr>
                    <th>ลำดับ</th>
                    <th>ชื่อ-นามสกุล</th>
                    <th>เอกสารสิทธิ</th>
                    <th>เลขที่เอกสารสิทธิ</th>
                    <th>ไร่</th>
                    <th>งาน</th>
                    <th>ตารางวา</th>
                    <th>พื้นที่</th>

                    <th>สถานะ</th>
                    <th></th>
                </tr>
            </tfoot>

            <tbody>

                @{
                        var textstatus = "รออนุมัติ";
                        var textstatus2 = "อนุมัติ";
                        int ii = 1; 

                        foreach (adminModel land in ViewBag.land)
                        {

                        <tr>
                             <td width="2%">@ii</td>
                            <td width="13%"><a href="@Url.Action("showland", "Home",new { id = land.o_land_id })"> @land.o_name @land.o_surname</a></td>
                             <td width="11%">@land.name_type</td>
                            <td width="11%">@land.o_land_num</td>
                            <td width="10%">@land.land_rai</td>
                            <td width="10%">@land.land_nga</td>
                            <td width="10%">@land.land_va</td>
                            <td width="20%">จ.@land.PROVINCE_NAME อ.@land.AMPHUR_NAME ต.@land.DISTRICT_NAME</td>

                            <td width="5%">

                                @if (land.status_land == "1")
                                    {
                                    <font color='red'> @textstatus</font>
                                }
                            @if (land.status_land == "2")
                                    {
                                    <font color='green'> @textstatus2</font>
                                }
                            </td>
                            <td width="5%">
                                <a href="@Url.Action("formimg", "Home",new { o_land_id = land.o_land_id,land.PROVINCE_NAME,land.AMPHUR_NAME,land.DISTRICT_NAME,ViewBag.type_owner_land })"><i class="fa fa-file-image-o" style="font-size:24px; color:cornflowerblue;"></i></a>

                                &nbsp; <a href="@Url.Action("focus_land", "Backend",new { o_land_id = land.o_land_id,land.PROVINCE_NAME,land.AMPHUR_NAME,land.DISTRICT_NAME,ViewBag.type_owner_land })"><i class="fa fa-map-marker" style="font-size:30px; color:red;"></i></a>


                            </td>
                            
                        </tr>
                        ii++;
                    }
                   
                }

            </tbody>
        </table>

    </div>
</div>

cmarket/Views/Backend/list_owner.cshtml
@using cmarket.Models
@model IEnumerable<adminModel>
@Scripts.Render("~/Content/backend/assets/js/jquery/jquery-1.9.1.min.js")
@{
    if (@Session["staff_id"] == null)
    {


        <script type='text/javascript'> window.location.href = '@Url.Action("ladmin", "Backend")';</script>
    }
}



<div class="panel panel-default">
    <!--<div class="panel-heading">
        <a href="#" data-column="0" class="toggle-vis btn btn-default btn-sm">Name</a>
        <a href="#" data-column="1" class="toggle-vis btn btn-default btn-sm">Position</a>
        <a href="#" data-column="2" class="toggle-vis btn btn-default btn-sm">Office</a>
        <a href="#" data-column="3" class="toggle-vis btn btn-default btn-sm">Age</a>
        <a href="#" data-column="4" class="toggle-vis btn btn-default btn-sm">Start date</a>
        <a href="#" data-column="5" class="toggle-vis btn btn-default btn-sm">Salary</a>
    </div>-->
    <div class="panel-body">


        @if (Convert.ToInt32(ViewData["type_status_regis"]) == 1)
        {
            <a href="@Url.Action("owner_land", "Backend", new { type_status_regis = 1 })">
                <button type="button" class="btn btn-success">เจ้าของที่ดิน</button>
            </a>
            <a href="@Url.Action("owner_land", "Backend", new { type_status_regis = 2 })">
                <button type="button" class="btn btn-default">ผู้ต้องการใช้ประโยชน์ในที่ดิน</button>
            </a>
        }

        @if (Convert.ToInt32(ViewData["type_status_regis"]) == 2)
        {
            <a href="@Url.Action("owner_land", "Backend", new { type_status_regis = 1 })">
                <button type="button" class="btn btn-default">เจ้าของที่ดิน</button>
            </a>
            <a href="@Url.Action("owner_land", "Backend", new { type_status_regis = 2 })">
                <button type="button" class="btn btn-success">ผู้ต้องการใช้ประโยชน์ในที่ดิน</button>
            </a>
        }





        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="basic-datatable2">
            <thead>
                <tr>
                    <th>ลำดับ</th>
                    <th>ชื่อ-นามสกุล</th>
                    <th>รหัสบัตรประชาชน</th>
                    <th>เบอร์โทร</th>
                    <th>จังหวัด</th>
                    <th>อำเภอ</th>
                    <th>ตำบล</th>
                    <th>จัดการ</th>
                </tr>
            </thead>

            <tfoot>
                <tr>
                    <th>ลำดับ</th>
                    <th>ชื่อ-นามสกุล</th>
                    <th>รหัสบัตรประชาชน</th>
                    <th>เบอร์โทร</th>
                    <th>จังหวัด</th>
                    <th>อำเภอ</th>
                    <th>ตำบล</th>
                    <th>จัดการ</th>
                </tr>
            </tfoot>

            <tbody>



                @{ int ii = 1; 
                foreach (adminModel owland in ViewBag.owland)
                {
                    
                    <tr>
                        <td>@ii</td>
                        <td>@owland.far_name @owland.far_surname</td>
                        <td>@owland.id_card</td>
                        <td>@owland.far_tel</td>
                        <td>@owland.PROVINCE_NAME</td>
                        <td>@owland.AMPHUR_NAME</td>
                        <td>@owland.DISTRICT_NAME</td>
                        <td>



                            <a href="#" data-toggle="tooltip" data-placement="top" title="ResetPassword">  <button class="btn btn-info btn-sm" data-toggle="modal" id="reset-@owland.far_id" data-target="#modal-form-reset-@owland.far_id"><i class="fa fa-key" style="font-size:20px"></i> </button> </a>

                            <a href="@Url.Content("~/HOME/data_farmer/")@owland.far_id">view</a>



                        </td>
                    </tr>
                    
                    <!-- Modal With Form -->

                    <div class="modal fade" id="modal-form-reset-@owland.far_id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>

                                </div>
                                <div class="modal-body">


                                    <form role="form">

                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Reset Password (@owland.far_name @owland.far_surname)</label>
                                            <input type="text" class="form-control" id="far_pass-@owland.far_id" name="far_pass" value="">
                                            <input type="hidden" class="form-control" id="far_id-@owland.far_id" placeholder="Enter email" value="@owland.far_id">
                                        </div>


                                    </form>

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary" id="send @owland.far_id" onclick="fcc('@owland.far_id')">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>


                    ii++;

                }
             }

            </tbody>
        </table>

    </div>
</div>

<div id="show_alert_pass"></div>

<script>

    function fcc(id) {
        //alert(id);



                $(document).ready(function ($) {



                    var far_id = $("#far_id-" + id).val();
                    var far_pass = $("#far_pass-" + id).val();
                    //alert(far_pass);

                                 var urlprov = "@Url.Content("~/HOME/resetpass_farmer/")" + id;
                                $.ajax({
                               // type: 'POST',
                                    url: '@Url.Content("~/Backend/resetpass_farmer/")' + far_id + "-"+ far_pass,
                                //dataType: "json", //กำหนดให้มีรูปแบบเป็น Json
                                //data: province_id, //ส่งค่าตัวแปร show_province เพื่อดึงข้อมูล จังหวัด
                                //data: { province_id: province_id },
                                    success: function (data) {

                                        //alert(AMPHUR_ID);
                                        //$("#DISTRICT_ID").text("");
                                       // $("#showtumbon").html("" + data);


                                        if (data == 1) {

                                            $("#show_alert_pass").html('<div class="alert_pass alert-success" role="alert" style="height:100px;"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong>Success!</strong> บันทึกข้อมูลแล้ว!</div>');
                                            $("#show_alert_pass").show();


                                            $("#far_pass-" + id).val("");

                                            window.setTimeout(function () {
                                                $(".alert_pass").fadeTo(500, 0).slideUp(500, function () {
                                                    $(this).remove();
                                                });
                                            }, 3000);
                                        }



                                }
                                });
                        });




    }



</script>